### ISSUE TITLE
MVP Functionality

### ISSUE THREAD

**Issue by curtisma** [cascode-labs/virtue#1]
**Problem Statement**
----------------------------

We need to create the initial minimal viable product.

**Action Plan**
-------------------------------
- [x] 1. Add SKILL libraries
- [x] 2. Ensure each library includes unit tests
- [x] 3. Create the documentation and publish it to GitHub pages
- [x] 4. Create the Python package
- [x] 5. Publish the Python package to PyPi
- [x] 6. Release v0.1.0
